### ISSUE TITLE
How i can uplaod yout bot in my server ?

### ISSUE THREAD

**Issue by LoicShmit** [Yuuko-oh/Yuuko#1]
Hello ! 

I would like to uplaod and use your bot in my server.

Can you have an installation guide or somone else who can help me ?

Thanks,
Loic

**Comment by BasketBandit** [comment]
Hey Loic,

If you just want the bot on your server, you can follow this [link](https://discordapp.com/oauth2/authorize?client_id=420682957007880223&permissions=8&scope=bot) which will invite the one that I am hosting. (I can give support in my support server)

If you wish to host it yourself, you'll need to download the project files, compile them into a jar, set up a database with the correct schema, then you'll need to get API keys for Transport for London, World of Warcraft, RuneScape and maybe others that I can't remember off the top of my head. These are then passed into the program via command line. Furthermore, you'd also need to setup a bot account with Discord and then add your key from that too.

However, since this is GitHub, you can also just remove the stuff you don't want if you wanna skip the hoops but at that point it'd be easy to start from scratch :P  

I hope this helps.
